channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.7.6

  - pip=21.1.1
  - pip:
    # Define pip packages here. 
    # https://pypi.org/
    - rpaframework==10.0.5 # https://rpaframework.org/releasenotes.html
